
["Skill Points"]
	#Range: 1 ~ 1000
	"Maximum skill points" = 85
	#Range: > 0
	"First skill point cost" = 15
	#Range: > 0
	"Last skill point cost" = 1400
	#You can set cost for each skill point instead
	"Use skill points costs array" = false
	#This list's size must be equal to maximum skill points.
	"Levelup costs" = [15, 19, 24, 30, 37, 45, 54, 64, 75, 87]
	#Disabling this will remove chat messages when you gain a skill point.
	"Show chat messages" = true
	#Warning: If you disable this make sure you make alternative way of getting skill points.
	"Enable exprerience exchange for skill points" = true

[Gems]
	#Range: 0.0 ~ 1.0
	"Base drop chance" = 0.15

[Equipment]
	#Range: 0 ~ 4
	"Default Helmets Sockets" = 1
	#Range: 0 ~ 4
	"Default Chestplates Sockets" = 1
	#Range: 0 ~ 4
	"Default Leggings Sockets" = 0
	#Range: 0 ~ 4
	"Default Boots Sockets" = 1
	#Range: 0 ~ 4
	"Default Weapons Sockets" = 1
	#Range: 0 ~ 4
	"Default Shields Sockets" = 1
	#Range: 0 ~ 4
	"Default Rings Sockets" = 1
	#Range: 0 ~ 4
	"Default Necklaces Sockets" = 1
	#You can remove sockets from items here
	#Example: Blacklisting specific items: ["minecraft:diamond_hoe", "minecraft:golden_hoe"]
	#Example: Blacklisting whole mod: ["<mod_id>:*"]
	#Example: Blacklisting all items: ["*:*"]
	"IDs of items that shouldn't have sockets" = []

#You can force items from other mods into equipmentType categories here
["Amnesia Scroll"]
	#How much levels (percentage) player lose using amnesia scroll
	#Range: 0.0 ~ 1.0
	"Amnesia scroll penalty" = 0.2
	"Drop amnesia scrolls from the Ender Dragon" = true

[Experience]
	#Range: 0.0 ~ 1.0
	"Grindstone experience multiplier" = 0.1

[Mixtures]
	#Range: 0.0 ~ 2.0
	"Effects duration multiplier" = 1.0
	#Range: 0.0 ~ 2.0
	"Effects strength multiplier" = 1.0

