
[Wegotrunnersrate]
	#currently 8 percent, increase for more runners
	"Runners Spawn Rate" = 0.08
	#currently 10 percent, increase for more grounders. (The less this is the more normal zombies spawn)
	"Grounders Scale Rate" = 0.1

["Runners Grouping"]
	#This will make runners spawn in group by converting nearby zombies
	"Runners Grouping" = true
	#How big is the radius for runners to convert normal zombies upon spawning
	"Runners Group size" = 18.0

["Iron Golem and Snowman Buffs"]
	"Iron Golem's Buff" = true
	"Snowman's Buff" = true

[particles]
	"Angry Particles" = true

